package com.permission.dao;

import com.permission.model.SysRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRoleMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_role
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_role
   *
   * @mbg.generated
   */
  int insert(SysRole record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_role
   *
   * @mbg.generated
   */
  int insertSelective(SysRole record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_role
   *
   * @mbg.generated
   */
  SysRole selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_role
   *
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(SysRole record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_role
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(SysRole record);

  List<SysRole> getAll();

  int countByName(@Param("name") String name, @Param("id") Integer id);
}